name: tmp preview repro
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number"
        required: true
        type: number

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  preview:
    uses: ./.github/workflows/app-deploy-preview.yml
    with:
      pr-number: ${{ inputs.pr_number }}
